# Generated by Django 4.1.3 on 2022-11-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactenquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enq_type', models.CharField(max_length=20)),
                ('c_name', models.CharField(max_length=30)),
                ('c_email', models.EmailField(max_length=254)),
                ('c_phone', models.CharField(max_length=10)),
                ('c_address', models.CharField(max_length=255)),
                ('c_country', models.CharField(max_length=25)),
                ('c_message', models.TextField()),
            ],
        ),
    ]
